spring.application.name=spring-project-14aprel
server.port=8085
app.name=MyApp
app.version=5

@ConfigurationProperties(prefix = "app") istifad\u0259 edin
AppConfig sinifi yarad\u0131n
name v\u0259 version field-l\u0259rini map edin